[package]
name = "test-suite"
version = "0.1.0"
edition = "2021"

[dependencies]
oxigraph = { version = "0.4.9", default-features = false }
oxrdfio = "0.1.7"
serde = {version="1.0.219", features=["derive"]}
serde_json = {version = "1.0.140"}
